language: node_js
sudo: false
node_js:
  - "7.0"
install:
  - npm install
  - npm install -g codecov
script:
  - nyc npm test
  - nyc report --reporter=text-lcov > coverage.lcov

after_success:
  - codecov
